### ISSUE TITLE
 NameError("name 'OPC' is not defined"), <traceback object at 0x000001D87B9E0D40>)

### ISSUE THREAD

**Issue by nandhakumarbalu** [ya-mouse/openopc#18]
Can anyone help me on this

Platform :Win 10 x64bit

When I use:

import OpenOPC
OPC.open_client('IP')

Getting the error as

 **(<class 'NameError'>, NameError("name 'OPC' is not defined"), <traceback object at 0x000001CD8C5CDF00>)**

**Comment by ya-mouse** [comment]
You should use:
```
OpenOPC.open_client(...)
```
